Check that GPU binary doesn't use too new glibc

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -138,7 +138,7 @@ jobs:
           artifactName: mmseqs-linux-$(SIMD)
 
   - job: build_ubuntu_gpu
-    displayName: Ubuntu MMseqs2
+    displayName: Ubuntu MMseqs2 GPU
     pool:
       vmImage: 'Ubuntu-20.04'
     timeoutInMinutes: 120
@@ -163,6 +163,14 @@ jobs:
             -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++" \
             -DENABLE_CUDA=1 -DCMAKE_CUDA_ARCHITECTURES="75-real;80-real;86-real;89-real;90" ..
           cmake --build . -j$(nproc --all)
+          # fail if GLIBC_PRIVATE or too new GLIBC is present
+          if readelf -Ws mmseqs | grep -q GLIBC_PRIVATE; then
+            exit 1
+          fi
+          LIBC_V=$(readelf -V mmseqs | awk '$3 ~ /^GLIBC_/ { print $3 }' | sort -V | tail -n1)
+          if [[ "$LIBC_V" > "GLIBC_2.29" ]]; then
+              exit 1
+          fi
         displayName: Build MMseqs2
       - task: PublishPipelineArtifact@0
         inputs:
